import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsBoolean,
  IsArray,
  ArrayNotEmpty,
} from 'class-validator';

export class CreateScheduleRuleDto {
  @ApiProperty({ example: '4 on / 3 off pattern' })
  @IsString()
  @IsNotEmpty()
  name: string;

  // Free-form pattern or will be autogenerated from the shiftTypes / dates below
  @ApiProperty({ example: '4on-3off', required: false })
  @IsOptional()
  @IsString()
  pattern?: string;

  @ApiProperty({ example: ['Normal', 'Rotational'], required: false })
  @IsOptional()
  @IsArray()
  @ArrayNotEmpty()
  shiftTypes?: string[];

  @ApiProperty({ example: '2025-11-01', required: false })
  @IsOptional()
  @IsString()
  startDate?: string;

  @ApiProperty({ example: '2025-12-01', required: false })
  @IsOptional()
  @IsString()
  endDate?: string;

  @ApiProperty({ example: true, required: false })
  @IsOptional()
  @IsBoolean()
  active?: boolean;

  // @ApiProperty({
  //   example: [0, 6],
  //   description: 'Weekly rest days 0=Sunday..6=Saturday',
  //   required: false,
  // })
  // @IsOptional()
  // @IsArray()
  // @ArrayNotEmpty()
  // weeklyRestDays?: number[];

  // @ApiProperty({
  //   example: ['2025-12-25', '2025-12-31'],
  //   description: 'Specific rest dates (YYYY-MM-DD)',
  //   required: false,
  // })
  // @IsOptional()
  // @IsArray()
  // @ArrayNotEmpty()
  // @IsString({ each: true })
  // @Matches(/^\d{4}-\d{2}-\d{2}$/, { each: true })
  // restDates?: string[];
}
